# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 15:50
from __future__ import unicode_literals

import address.models
import datastore.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageProficiencyOfFathersInReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', datastore.models.PercentField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageProficiencyOfFathersInSpeaking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', datastore.models.PercentField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageProficiencyOfFathersInUnderstanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', datastore.models.PercentField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageProficiencyOfFathersInWriting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', datastore.models.PercentField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageProficiencyOfMothersInReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', datastore.models.PercentField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageProficiencyOfMothersInSpeaking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', datastore.models.PercentField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageProficiencyOfMothersInUnderstanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', datastore.models.PercentField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageProficiencyOfMothersInWriting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', datastore.models.PercentField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguagesKnownByFatherInOrderOfFluency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguagesKnownByMotherInOrderOfFluency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSpokenToBabyByFather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', datastore.models.PercentField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSpokenToBabyByMaternalGrandparents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', datastore.models.PercentField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSpokenToBabyByMother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', datastore.models.PercentField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSpokenToBabyByOtherCaregivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', datastore.models.PercentField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSpokenToBabyByPaternalGrandparents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', datastore.models.PercentField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSpokenToBabyByRelatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', datastore.models.PercentField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSpokenToBabyBySiblings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', datastore.models.PercentField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSpokenToBabyInSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', datastore.models.PercentField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country_of_birth', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.CharField(choices=[('NARRATION', 'NARRATION'), ('PUPPET SHOW', 'PUPPET SHOW'), ('FORWARD-BACKWARD', 'FORWARD-BACKWARD'), ('NonAdj', 'NonAdj')], max_length=20)),
                ('recording', models.FileField(blank=True, null=True, upload_to='')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datastore.Person')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(blank=True, max_length=35, null=True)),
                ('date_of_birth', models.DateField()),
                ('has_sight_difficulties', models.NullBooleanField()),
                ('has_hearing_difficulties', models.NullBooleanField()),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('language_spoken_in_home_between_parents', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_spoken_in_home_between_siblings', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_spoken_in_home_between_maternal_grandparents', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_spoken_in_home_between_paternal_grandparents', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_spoken_in_home_between_parents_and_other_relatives', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_spoken_in_home_between_parents_and_other_caregivers', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_used_in_home_for_reading', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_used_in_home_for_listening_to_radio_or_music', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_used_in_home_for_watching_tv_or_video', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_used_in_home_for_using_internet_or_smartphones', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_used_in_home_for_reading_stories_to_child', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('number_of_weekly_hours_spent_with_child_by_mother', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('number_of_weekly_hours_spent_with_child_by_father', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('number_of_weekly_hours_spent_with_child_by_siblings', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('number_of_weekly_hours_spent_with_maternal_grandparents', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('number_of_weekly_hours_spent_with_paternal_grandparents', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('number_of_weekly_hours_spent_with_child_by_other_relatives', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('number_of_weekly_hours_spent_with_child_by_school', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('language_child_speaks_to_mother', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_child_speaks_to_father', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_child_speaks_to_siblings', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_child_speaks_to_maternal_grandparents', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_child_speaks_to_paternal_grandparents', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_child_speaks_to_other_relatives', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_child_speaks_to_friends', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_child_uses_for_reading', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_child_uses_for_listening_to_radio_or_music', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_child_uses_for_watching_tv_or_video', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_child_uses_internet_or_smartphones_in', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_child_uses_overall_to_speak_at_home', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
                ('language_child_uses_overall_to_speak_within_your_community', models.IntegerField(choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')])),
            ],
            bases=('datastore.person',),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datastore.Person')),
                ('date_of_migration_to_singapore', models.DateField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
            ],
            bases=('datastore.person',),
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datastore.Parent')),
            ],
            bases=('datastore.parent',),
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datastore.Parent')),
            ],
            bases=('datastore.parent',),
        ),
        migrations.AddField(
            model_name='session',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Baby'),
        ),
        migrations.AddField(
            model_name='parent',
            name='home_address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
        migrations.AddField(
            model_name='parent',
            name='languages_spoken_while_growing_up',
            field=models.ManyToManyField(blank=True, related_name='parent', to='datastore.Language'),
        ),
        migrations.AddField(
            model_name='languagespokentobabyinschool',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Baby'),
        ),
        migrations.AddField(
            model_name='languagespokentobabybysiblings',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Baby'),
        ),
        migrations.AddField(
            model_name='languagespokentobabybyrelatives',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Baby'),
        ),
        migrations.AddField(
            model_name='languagespokentobabybypaternalgrandparents',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Baby'),
        ),
        migrations.AddField(
            model_name='languagespokentobabybyothercaregivers',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Baby'),
        ),
        migrations.AddField(
            model_name='languagespokentobabybymother',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Baby'),
        ),
        migrations.AddField(
            model_name='languagespokentobabybymaternalgrandparents',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Baby'),
        ),
        migrations.AddField(
            model_name='languagespokentobabybyfather',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Baby'),
        ),
        migrations.AddField(
            model_name='languagesknownbymotherinorderoffluency',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Mother'),
        ),
        migrations.AddField(
            model_name='languagesknownbyfatherinorderoffluency',
            name='father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Father'),
        ),
        migrations.AddField(
            model_name='languageproficiencyofmothersinwriting',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Mother'),
        ),
        migrations.AddField(
            model_name='languageproficiencyofmothersinunderstanding',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Mother'),
        ),
        migrations.AddField(
            model_name='languageproficiencyofmothersinspeaking',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Mother'),
        ),
        migrations.AddField(
            model_name='languageproficiencyofmothersinreading',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Mother'),
        ),
        migrations.AddField(
            model_name='languageproficiencyoffathersinwriting',
            name='father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Father'),
        ),
        migrations.AddField(
            model_name='languageproficiencyoffathersinunderstanding',
            name='father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Father'),
        ),
        migrations.AddField(
            model_name='languageproficiencyoffathersinspeaking',
            name='father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Father'),
        ),
        migrations.AddField(
            model_name='languageproficiencyoffathersinreading',
            name='father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Father'),
        ),
        migrations.AddField(
            model_name='baby',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baby', to='datastore.Father'),
        ),
        migrations.AddField(
            model_name='baby',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baby', to='datastore.Mother'),
        ),
    ]
