# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='language_child_speaks_to_father',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_child_speaks_to_friends',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_child_speaks_to_maternal_grandparents',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_child_speaks_to_mother',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_child_speaks_to_other_relatives',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_child_speaks_to_paternal_grandparents',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_child_speaks_to_siblings',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_child_uses_for_listening_to_radio_or_music',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_child_uses_for_reading',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_child_uses_for_watching_tv_or_video',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_child_uses_internet_or_smartphones_in',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_child_uses_overall_to_speak_at_home',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_child_uses_overall_to_speak_within_your_community',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_spoken_in_home_between_maternal_grandparents',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_spoken_in_home_between_parents',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_spoken_in_home_between_parents_and_other_caregivers',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_spoken_in_home_between_parents_and_other_relatives',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_spoken_in_home_between_paternal_grandparents',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_spoken_in_home_between_siblings',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_used_in_home_for_listening_to_radio_or_music',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_used_in_home_for_reading',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_used_in_home_for_reading_stories_to_child',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_used_in_home_for_using_internet_or_smartphones',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='language_used_in_home_for_watching_tv_or_video',
            field=models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')]),
        ),
    ]
