# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0006_auto_20170619_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='occupation_link',
            new_name='occupation',
        ),
    ]
