# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 13:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0007_auto_20170619_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyLanguageProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('language_spoken_in_home_between_parents', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_spoken_in_home_between_siblings', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_spoken_in_home_between_maternal_grandparents', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_spoken_in_home_between_paternal_grandparents', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_spoken_in_home_between_parents_and_other_relatives', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_spoken_in_home_between_parents_and_other_caregivers', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_used_in_home_for_reading', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_used_in_home_for_listening_to_radio_or_music', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_used_in_home_for_watching_tv_or_video', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_used_in_home_for_using_internet_or_smartphones', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_used_in_home_for_reading_stories_to_child', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('number_of_weekly_hours_spent_with_child_by_mother', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('number_of_weekly_hours_spent_with_child_by_father', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('number_of_weekly_hours_spent_with_child_by_siblings', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('number_of_weekly_hours_spent_with_maternal_grandparents', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('number_of_weekly_hours_spent_with_paternal_grandparents', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('number_of_weekly_hours_spent_with_child_by_other_relatives', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('number_of_weekly_hours_spent_with_child_by_school', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('language_child_speaks_to_mother', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_child_speaks_to_father', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_child_speaks_to_siblings', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_child_speaks_to_maternal_grandparents', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_child_speaks_to_paternal_grandparents', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_child_speaks_to_other_relatives', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_child_speaks_to_friends', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_child_uses_for_reading', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_child_uses_for_listening_to_radio_or_music', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_child_uses_for_watching_tv_or_video', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_child_uses_internet_or_smartphones_in', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_child_uses_overall_to_speak_at_home', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
                ('language_child_uses_overall_to_speak_within_your_community', models.IntegerField(blank=True, choices=[(1, 'All English'), (2, '2'), (3, '3'), (4, 'Half English/half other language'), (5, '5'), (6, '6'), (7, 'All 2nd Language')], null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_child_speaks_to_father',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_child_speaks_to_friends',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_child_speaks_to_maternal_grandparents',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_child_speaks_to_mother',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_child_speaks_to_other_relatives',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_child_speaks_to_paternal_grandparents',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_child_speaks_to_siblings',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_child_uses_for_listening_to_radio_or_music',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_child_uses_for_reading',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_child_uses_for_watching_tv_or_video',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_child_uses_internet_or_smartphones_in',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_child_uses_overall_to_speak_at_home',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_child_uses_overall_to_speak_within_your_community',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_spoken_in_home_between_maternal_grandparents',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_spoken_in_home_between_parents',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_spoken_in_home_between_parents_and_other_caregivers',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_spoken_in_home_between_parents_and_other_relatives',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_spoken_in_home_between_paternal_grandparents',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_spoken_in_home_between_siblings',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_used_in_home_for_listening_to_radio_or_music',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_used_in_home_for_reading',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_used_in_home_for_reading_stories_to_child',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_used_in_home_for_using_internet_or_smartphones',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='language_used_in_home_for_watching_tv_or_video',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='number_of_weekly_hours_spent_with_child_by_father',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='number_of_weekly_hours_spent_with_child_by_mother',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='number_of_weekly_hours_spent_with_child_by_other_relatives',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='number_of_weekly_hours_spent_with_child_by_school',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='number_of_weekly_hours_spent_with_child_by_siblings',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='number_of_weekly_hours_spent_with_maternal_grandparents',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='number_of_weekly_hours_spent_with_paternal_grandparents',
        ),
        migrations.RemoveField(
            model_name='languagespokentobabybyfather',
            name='baby',
        ),
        migrations.RemoveField(
            model_name='languagespokentobabybymaternalgrandparents',
            name='baby',
        ),
        migrations.RemoveField(
            model_name='languagespokentobabybymother',
            name='baby',
        ),
        migrations.RemoveField(
            model_name='languagespokentobabybyothercaregivers',
            name='baby',
        ),
        migrations.RemoveField(
            model_name='languagespokentobabybypaternalgrandparents',
            name='baby',
        ),
        migrations.RemoveField(
            model_name='languagespokentobabybyrelatives',
            name='baby',
        ),
        migrations.RemoveField(
            model_name='languagespokentobabybysiblings',
            name='baby',
        ),
        migrations.RemoveField(
            model_name='languagespokentobabyinschool',
            name='baby',
        ),
        migrations.AddField(
            model_name='babylanguageprofile',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_profiles', to='datastore.Baby'),
        ),
        migrations.AddField(
            model_name='languagespokentobabybyfather',
            name='language_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages_spoken_to_baby_by_father', to='datastore.BabyLanguageProfile'),
        ),
        migrations.AddField(
            model_name='languagespokentobabybymaternalgrandparents',
            name='language_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages_spoken_to_baby_by_maternal_grandparents', to='datastore.BabyLanguageProfile'),
        ),
        migrations.AddField(
            model_name='languagespokentobabybymother',
            name='language_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages_spoken_to_baby_by_mother', to='datastore.BabyLanguageProfile'),
        ),
        migrations.AddField(
            model_name='languagespokentobabybyothercaregivers',
            name='language_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages_spoken_to_baby_by_other_caregivers', to='datastore.BabyLanguageProfile'),
        ),
        migrations.AddField(
            model_name='languagespokentobabybypaternalgrandparents',
            name='language_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages_spoken_to_baby_by_paternal_grandparents', to='datastore.BabyLanguageProfile'),
        ),
        migrations.AddField(
            model_name='languagespokentobabybyrelatives',
            name='language_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages_spoken_to_baby_by_relatives', to='datastore.BabyLanguageProfile'),
        ),
        migrations.AddField(
            model_name='languagespokentobabybysiblings',
            name='language_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages_spoken_to_baby_by_siblings', to='datastore.BabyLanguageProfile'),
        ),
        migrations.AddField(
            model_name='languagespokentobabyinschool',
            name='language_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages_spoken_to_baby_in_school', to='datastore.BabyLanguageProfile'),
        ),
    ]
