# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0008_auto_20170619_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagespokentobabybyfather',
            name='language_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages_spoken_to_baby_by_father', to='datastore.BabyLanguageProfile'),
        ),
        migrations.AlterField(
            model_name='languagespokentobabybymaternalgrandparents',
            name='language_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages_spoken_to_baby_by_maternal_grandparents', to='datastore.BabyLanguageProfile'),
        ),
        migrations.AlterField(
            model_name='languagespokentobabybymother',
            name='language_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages_spoken_to_baby_by_mother', to='datastore.BabyLanguageProfile'),
        ),
        migrations.AlterField(
            model_name='languagespokentobabybyothercaregivers',
            name='language_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages_spoken_to_baby_by_other_caregivers', to='datastore.BabyLanguageProfile'),
        ),
        migrations.AlterField(
            model_name='languagespokentobabybypaternalgrandparents',
            name='language_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages_spoken_to_baby_by_paternal_grandparents', to='datastore.BabyLanguageProfile'),
        ),
        migrations.AlterField(
            model_name='languagespokentobabybyrelatives',
            name='language_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages_spoken_to_baby_by_relatives', to='datastore.BabyLanguageProfile'),
        ),
        migrations.AlterField(
            model_name='languagespokentobabybysiblings',
            name='language_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages_spoken_to_baby_by_siblings', to='datastore.BabyLanguageProfile'),
        ),
        migrations.AlterField(
            model_name='languagespokentobabyinschool',
            name='language_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages_spoken_to_baby_in_school', to='datastore.BabyLanguageProfile'),
        ),
    ]
