# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 20:29
from __future__ import unicode_literals

import address.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('datastore', '0011_auto_20170619_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='home_address',
        ),
        migrations.AddField(
            model_name='father',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
        migrations.AddField(
            model_name='household',
            name='house_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='mother',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
