# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0013_auto_20170619_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='medical_history_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
